### ISSUE TITLE
skystone in AE2

### ISSUE THREAD

**Issue by Brokenbonesbg** [SnowShock35/TheRisingWorld-Modpack#1]
there might be something wrong with worldgen. AE2 meteors arnt spawning even when i turn the chances up to 100%. i spawned in a compass and looked for about 30 mins all it did was spin continuously

**Comment by SnowShock35** [comment]
Sorry for not mentioning this on the forum page (will add it in an hour or so) If you look at the presses in NEI you'll probably find that there have crafting recipes. This is done to stop people from constantly exploring to find the 4 presses. Also skystone is obtainable by low world gen an crafting recipe ;)

-Snow
